steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Build static assets
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build the production Docker image (uses Dockerfile from the build context)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/podcast-frontend:$BUILD_ID'
      - '.'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/podcast-frontend:$BUILD_ID']

  # Deploy the specific image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'podcast-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/podcast-frontend:$BUILD_ID'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

# Specify the image to be pushed
images:
  - 'gcr.io/$PROJECT_ID/podcast-frontend:$BUILD_ID'

# Optional: Increase timeout
# timeout: '1200s' 