steps:
  # Build the application
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/podcast-migration', '.', '-f', 'backend/Dockerfile.migration']

  # Run the migration script
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/podcast-migration']

timeout: '1800s'  # 30 minutes 